[package]
name = "md_concat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] } # Use the latest version available
walkdir = "2.4" # Useful for directory traversal